### ISSUE TITLE
Add a follow button on a regular WP page. How to send email?

### ISSUE THREAD

**Issue by ARCangelGIRL** [r-a-y/buddypress-followers#104]
Hello,
I followed this to add follow button in different places in the website. 
https://github.com/r-a-y/buddypress-followers/wiki/Add-a-follow-button-on-a-regular-WP-page 
Below is my code.
```
if ( function_exists( 'bp_follow_add_follow_button' ) ) :
	if ( bp_loggedin_user_id() && bp_loggedin_user_id() != $getUserID ) {
		bp_follow_add_follow_button( array(
			'leader_id'   => $getUserID,
			'follower_id' => bp_loggedin_user_id()
		) );
	}
endif;
```

I use Buddypress. Follow button was added in member header and in one other page that is outside the member loop. What I would like to do - when somebody follows members, send an email. 
In member loop when following somebody, email is sent, but using this snippet no email were sent. 
I was checking around in plugin files, but can't figure it out how to do it. Could you help me with this?

**Comment by maxledoux** [comment]
You didn't define `$getUserId`.

**Comment by ARCangelGIRL** [comment]
`$getUserId` defined in my code, just didn't paste it here.
Everything works fine, user can follow and unfollow other member, just the email is not sent at all like it is if I follow from member loop.

**Comment by maxledoux** [comment]
Email is probably triggered by a hook that you're not calling.

**Comment by maxledoux** [comment]
`do_action ('bp_follow_start_following');`?

**Comment by ARCangelGIRL** [comment]
Could you advice me where exactly I should place this action in above code?

**Comment by maxledoux** [comment]
It would go like this:
```php
if ( function_exists( 'bp_follow_add_follow_button' ) ) :
	if ( bp_loggedin_user_id() && bp_loggedin_user_id() != $getUserID ) {
		bp_follow_add_follow_button( array(
			'leader_id'   => $getUserID,
			'follower_id' => bp_loggedin_user_id()
		) );
		do_action ('bp_follow_start_following');
	}
endif;
```

**Comment by ARCangelGIRL** [comment]
Actually I was doing the same, but all I get is the following:

> Catchable fatal error: Argument 1 passed to bp_follow_notifications_add_on_follow() must be an instance of BP_Follow, string given in .../wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php on line 95

**Comment by ARCangelGIRL** [comment]
Can it be happening because I'm using PHP version 5.6 and not 7.2 like it's suggested in Wordpress documentation?

**Comment by maxledoux** [comment]
>Can it be happening because I'm using PHP version 5.6 and not 7.2 like it's suggested in Wordpress documentation?

No, but you should update to 7.2 anyway. 5.x will no longer be supported after the end of the year.

```php
Catchable fatal error: Argument 1 passed to bp_follow_notifications_add_on_follow() must be an instance of BP_Follow, string given in .../wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php on line 95
```

Sorry, my bad. You would have to pass the `leader_id` and `follower_id` arguments through the action. I.E. `do_action ( 'bp_follow_start_following', $args );`. 

However, I'm smacking my forehead for my previous suggestion because that would send an email whenever the _page_ is loaded, not when the button is clicked. Whoops. So, you should abandon that snippet. Sorry, I was being a bone head.

🤦‍♂️

**Comment by ARCangelGIRL** [comment]
Yeah, that's true. Didn't thought about it, that email  will be sent every time page is loaded :)
I will try to find another way to fix this.

**Comment by r-a-y** [comment]
The information in this thread is incorrect.  Follow hooks are automatically fired when a person follows another person.  You don't need to add any `do_action()` codes or whatever.

However, one important thing to note is the follow email is only sent once.  If person B unfollows person A and tries to follows person A again, person A will not get a subsequent email about how person B just followed them.

I'm going to close this as this isn't a problem with the code.  However, feel free to continue replying to one another.

**Comment by epgb101** [comment]
Hi Ray/all..
This plugin works brilliantly on my site but I'm tweaking the text so I can use it as a Like feature. 
How do I edit the email text that gets sent to users in the newest plugin update (2023) that says;
Subject: Userx is now following you
Userx is now following your activity.

Any help for novice would be very much appreciated.
Ed
