### ISSUE TITLE
Having trouble Identifying Error

### ISSUE THREAD

**Issue by JordTheFraud** [r-a-y/buddypress-followers#112]
Hi all, 

I'm getting this error but I'm technically qualified enough to diagnose it. Can somebody help me out, please? 

it does follow the user, however. 

`Fatal error: Uncaught Error: [] operator not supported for strings in /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php:308 Stack trace: #0 /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php(122): bp_follow_new_follow_email_notification(Array) #1 /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-includes/class-wp-hook.php(288): bp_follow_notifications_add_on_follow(Object(BP_Follow)) #2 /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #3 /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #4 /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-content/plugins/buddypress-followers/_inc/bp-follow-functions.php(43): do_action_ref_array('bp_follow_start...', Array) #5 /homepages/28/ in /homepages/28/d804411185/htdocs/clickandbuilds/ThunderandMiles/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php on line 308`

error screenshot - [https://ibb.co/3ygv1SG](https://ibb.co/3ygv1SG)

thank you.

**Comment by mrjarbenne** [comment]
Have you attempted to revert to one of the default themes? That would be a first step to ensure it's not an issue with your theme. 

If you eliminate that, the next steps would be to deactivate all of the plugins on your site, then re-enable them one by one to see if you can find a collision between this plugin and another one you are running.

**Comment by r-a-y** [comment]
This is fixed in 1.2.x branch.

You can download a copy of it here: https://github.com/r-a-y/buddypress-followers/archive/1.2.x.zip
