### ISSUE TITLE
Follow/Unfollow Button in post template

### ISSUE THREAD

**Issue by Pintolus** [r-a-y/buddypress-followers#65]
Any idea how to add the follow/unfollow button in every single post (single.php)?

Thank you!

**Comment by Pintolus** [comment]
https://github.com/r-a-y/buddypress-followers/wiki/Add-a-follow-button-on-a-regular-WP-page

**Comment by Pintolus** [comment]
Awesome plugin! Keep up the good work!

**Comment by ezkay** [comment]
Nothing happens if i drop this into the `single.php`. Anyone here who can help me out?

`<?php
if ( function_exists( 'bp_follow_add_follow_button' ) ) :
    if ( bp_loggedin_user_id() && bp_loggedin_user_id() != get_the_author_meta( 'ID' ) ) {
        bp_follow_add_follow_button( array(
            'leader_id'   => get_the_author_meta( 'ID' ),
            'follower_id' => bp_loggedin_user_id()
        ) );
    }
endif;
?>`
