### ISSUE TITLE
`bp_follow_stop_following()` throws error if follow does not exist

### ISSUE THREAD

**Issue by boonebgorges** [r-a-y/buddypress-followers#69]
`bp_follow_stop_following()`, if called with a leader_id/follower_id/follow_type triplet that doesn't correspond to an actual follow, will throw a notice. It has something to do with the `BP_Follow` object having an `id` of `0` in this case, which breaks the way the WHERE conditions are built. 

It's not a big deal, though it's inconvenient to have to do an is-following check before calling `stop_following()`. It might be nice in these cases to return `false` or something like that.

**Comment by r-a-y** [comment]
Thanks @boonebgorges.

Fixed!
