### ISSUE TITLE
WordPress version of this plugin not updated

### ISSUE THREAD

**Issue by espellcaste** [r-a-y/buddypress-followers#72]
This plugin on WordPress is not the same as the one the master branch here. The WordPress one still has some errors such as the WP_Widget one.

**Comment by r-a-y** [comment]
Sorry about that, @espellcaste!

I've been meaning to release a maintenance release for the 1.2.x branch:
https://github.com/r-a-y/buddypress-followers/tree/1.2.x

The Git SVN release script I use does not handle multiple Git branches properly.  That's kind of the hold up.

**Comment by r-a-y** [comment]
Just released v1.2.2, which is a maitenance release that primarily fixes the `WP_Widget` notice and a few other minor things in 1.2-branch.

**Comment by espellcaste** [comment]
Cool! Thanks! =)
