### ISSUE TITLE
Improve bp_follow_notification_message filter

### ISSUE THREAD

**Issue by renatonascalves** [r-a-y/buddypress-followers#76]
I'd like to make a suggestion to improve this filter adding more information as params. As of right now, only $message, $follower_name, $follower_link is allowed.

I suggest adding:

- $follower_id
- $following_id (Person being followed)

With those both ids, one can use them to fetch more information if needed when customizing the message.

What do you think @r-a-y?

**Comment by r-a-y** [comment]
v1.3 will introduce support for BP 2.5 emails (#74), which will allow site admins to customize the text in the Emails dashboard and will probably make this filter irrelevant :)

I can still add the parameters if you want me to.

**Comment by renatonascalves** [comment]
Got it! No, I already added in my local setup. I thought it would be interesting for other devs. But you made a good point. =)
