### ISSUE TITLE
Followers breaks front.php

### ISSUE THREAD

**Issue by robidob** [r-a-y/buddypress-followers#82]
The followers plugin makes the new front.php template feature on buddypress 2.6 not work properly.
Just on the member's front.php. No problem with groups front.php
My install is WP 4.5.3 BP 2.6.1.1

**Comment by renatonascalves** [comment]
What error are you getting?

**Comment by robidob** [comment]
No error message. Just, instead of going to the profile home it opens a blog archive with no profile header or navigation.  It only happens when I try to use the front.php as a profile home. See screenshot.
BP Follow version 1.2.2
![followers-on-off-screenshot](https://cloud.githubusercontent.com/assets/20388681/16752407/fd165d7e-4795-11e6-80af-864cf531be8d.jpg)

**Comment by r-a-y** [comment]
I cannot duplicate your problem.

What is in your `front.php` template, @robidob ?

**Comment by renatonascalves** [comment]
I also can't replicate this issue... :/

Try to activate WP_DEBUG to make sure if errors is being shown.

**Comment by robidob** [comment]
It turned out there must be a problem with my theme setup. I have just tried it on a fresh install with Twentysixteen and it worked fine.
Thank you for your time, I really appreciate it. And my apologies for the inconvenience.

**Comment by renatonascalves** [comment]
@robidob No problem!
