### ISSUE TITLE
Post deletion notification

### ISSUE THREAD

**Issue by renatonascalves** [r-a-y/buddypress-followers#84]
@r-a-y I'd like your feedback here.

I'm considering what's the correct approach when an admin, editor or author is deleting a post that has users following it. What should show to the person doing the action (deleting the post) and should the user following the post be informed by email?

**Comment by r-a-y** [comment]
If you think about this more generally:

- Facebook and Twitter doesn't inform you if a user stops being your friend or if a user stops following you.
- When you are subscribed to a blog post's comments (via whatever subscription mechanism), you do not receive an email once an author deletes their post.

So I would say do not send any response to the follower.  However, this is totally up to you!

**Comment by renatonascalves** [comment]
Got it! Thanks!
