### ISSUE TITLE
Wrong button css

### ISSUE THREAD

**Issue by RostiMelk** [r-a-y/buddypress-followers#86]
Hi, seems like i have a styling problem for my followers button, I'm not that good with css so help would be greatly appreciated, I'm using the woffice theme.

![f09d54a35fb24b08b8ea32bef26af2c2](https://cloud.githubusercontent.com/assets/25268506/22289242/e19035f6-e2fa-11e6-920c-2f2b2590d1a5.png)

Look at the button on the picture.

**Comment by r-a-y** [comment]
Thanks for posting, but this is not the proper place for user support questions.  Also your theme is a premium theme so I cannot offer support for that.

You'll need to tell Woffice to add support for BP Follow.  Woffice is probably using some custom CSS with an icon font, so there's your first clue.

Here's a site that offers icon fonts:
http://weloveiconfonts.com/

They also have a tutorial you could read.  You'll need to figure out what icon font Woffice is using and what icon you'd want to use.
