### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ajitjohnson** [r-a-y/buddypress-followers#90]
I was wondering if it is possible to follow categories or custom taxonomy like it is possible to follow users. 

So that it becomes possible to include posts in categories/ custom taxonomies within the follow activity loop. 

I am not sure if this option is already available, if so please let me know. Else, I think this will be an awesome addition for people looking to develop a custom newsfeed for users.

**Comment by r-a-y** [comment]
Anything is possible; the capability is there in the codebase.  There would be problems with trying to get this to work on multisite though.

But, unfortunately I will not be working on anything like this in my spare time.
