### ISSUE TITLE
WordPress.org 2 years with no update

### ISSUE THREAD

**Issue by shay1383** [r-a-y/buddypress-followers#95]
Hi Ray
I have noticed that bp follow plugin at wordpress.org haven't been updated for 2 years, however here on GitHub it was modified on last August
What version you recommend to use? wordpress.org which is your official release or github?
Thank you
Shay.

**Comment by shay1383** [comment]
Ray please respond

**Comment by r-a-y** [comment]
There is nothing wrong with the v1.2.x series on wordpress.org.

Yes, it's been awhile, but I'm just one person working on this and do so mostly in my free time.  Unfortunately, other items have taken priority.  That being said, some plugins and projects have also had long release development cycles.  bbPress is one of them.

The Github version is the in-development version for v1.3.0.  It will be released when I deem it ready.  You are free to use it or not.  I don't really see any bugs with the working version though.  If you do, report them.

FYI, Github is a place to report bugs.  If you feel the need to post these types of things, do so on the wordpress.org support forum.
