### ISSUE TITLE
Deprecated: Function create_function() is deprecated

### ISSUE THREAD

**Issue by alief17** [r-a-y/buddypress-followers#99]
This plugin has not been updated for so long. Please fix this. Got an error that there's deprecated create_function().

Deprecated: Function create_function() is deprecated in /buddypress-followers/_inc/bp-follow-widgets.php on line 113

**Comment by r-a-y** [comment]
This is fixed in master branch, but not in 1.2.x.

Just backported commit 29ce249a to 1.2.x branch - see commit 3e38fc6.

You can download the latest 1.2.x branch here - https://github.com/r-a-y/buddypress-followers/archive/1.2.x.zip

**Comment by AiratHalitov** [comment]
@r-a-y 
The same issue here:
https://github.com/r-a-y/buddypress-followers/blob/3d82e212eb5f586784ffd282dcc5d24c1b5f8517/loader.php#L40-L42
and here:
https://github.com/r-a-y/buddypress-followers/blob/3d82e212eb5f586784ffd282dcc5d24c1b5f8517/_inc/users/screens.php#L124-L126
